PxAPI-2.yml

Made the discontinued property nullable on the table definition

Made discontinued nullable

---

PxAPI-2.yml
examples/table-metadata-example.json
generator/myGen.bat

Fixed the response object for the table metadata

TableMetadata update

---

PxAPI-2.yml

Added endpoints for
- listing code lists associated to a table
- displaying information for a specific code list
and types that defines the corresponding responses.

Added definitions and endpoints for codelist

---

PxAPI-2.yml

Added reference to the codeListId-parameter (SwaggerEditor complains)
Moved Values from AbstractCodeListVariable to AbstractVariable, so that Time and Contents also has it.

Added reference to the codeListId-parameter. Moved Values

---

PxAPI-2.yml

https://github.com/statisticssweden/PxApiSpecs/issues/55

Changed where values are attached to its variable, fixes 55

---

PxAPI-2.yml
examples/filter-agg_RegionNUTS2_2008.json
examples/filter-vs_RegionLän07.json
examples/table-metadata-example.json

This PR contains reordering of properties in the schemes and which properties should be required.
It also includes other minor fixes like improved comments

Miscellaneous fixes on the schamas

---

PxAPI-2.yml

Added missing Lanuage parameter to endpoints and to responses.

Added missing language parameter and attributes

---

PxAPI-2.yml

Moved ListAllTables from navigation and removed the endpoint to list all tables for a specific table.

Moved ListAllTables to Table

---

PxAPI-2.yml

Added a config  output for default data format and a output for available data formats and also the output query parameter to the tables data endpoint

Added data formats

---

PxAPI-2.yml

Renamed
- CodeList -> CodeListResponse
- TableMetadata -> TableMetadataResponse

Added Resonse to response objects

---

PxAPI-2.yml

Added an optional parameter outputFormats to the datable data endpoint.

With outputFormat when POSTing to table data.

---

.github/workflows/nuget.yml

Change when the action triggers no it triggers on Release

Trigger build nuget package to OnRelease

---

src/PxWeb.Api2.Server.Models/PxWeb.Api2.Server.Models.csproj
src/PxWeb.Api2.Server/PxWeb.Api2.Server.csproj

https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link

Do not include git commit id as we display this version info in PxWebApi

---

.openapi-generator/FILES
PxAPI-2.yml
src/PxWeb.Api2.Server.Models/VariablePlacementType.cs
src/PxWeb.Api2.Server/Controllers/TableApi.cs

Pivot functionality is added to data and default selection endpoints

Added pivot

---

PxAPI-2.yml
src/PxWeb.Api2.Server.Models/SelectionResponse.cs
src/PxWeb.Api2.Server.Models/VariablesSelection.cs

Fixed type-o in spec `Placement` instead of `Palcement`
Removed the extra `selection`  property in `SelectionResponse`

Misc fixes in spec

---

PxAPI-2.yml
src/PxWeb.Api2.Server/Controllers/TableApi.cs

Added OutputFormatParams parameter to the tables data endpoint

Added OutputFormatParams

---

src/PxWeb.Api2.Server.Models/PxWeb.Api2.Server.Models.csproj

This will make it possible to use the json-stat2 model in [PCAxis.Serializers](https://github.com/PxTools/PCAxis.Serializers)

Multi-target the Models project

---

PxAPI-2.yml
src/PxWeb.Api2.Server/Controllers/TableApi.cs

Added an optional codelist parameter that can be used to select specific codelists.

PXWEB2-726 Add codelist parameter to metadata endpoint 

---

PxAPI-2.yml
src/PxWeb.Api2.Server.Models/Table.cs

Added `subjectCode` to `TablesResponse` and `TableResponse`

Add subject code

---

PxAPI-2.yml
src/PxWeb.Api2.Server/Controllers/SavedQueriesApi.cs
src/PxWeb.Api2.Server/Controllers/TableApi.cs

Add `savedQuery` parameter to `GetMetadataById` and implement `GetSavedQuerySelection` endpoint

Added saved query parameters to metadata endpoint and new endpoint under savedqueries that show the selection 
